name: prom-label-proxy merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
jobs:
  prom-label-proxy-merge:
    uses: rhobs/syncbot/.github/workflows/merge-flow.yaml@main
    with:
      upstream: prometheus-community/prom-label-proxy
      downstream: openshift/prom-label-proxy
      sandbox: rhobs/prom-label-proxy
      go-version: "1.20"
      restore-downstream: >-
         OWNERS
      restore-upstream: >-
         CHANGELOG.md
         VERSION
         go.mod
         go.sum
         examples
         README.md
         main.go
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
