# This workflow will be triggered from repective component's prow CI post-merge job.
# Refer https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
name: Synchronize component versions in cluster-monitoring-operator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
jobs:
  versions-update:
    uses: rhobs/syncbot/.github/workflows/cmo-make-targets.yaml@main
    with:
      go-version: "1.20"
      make-targets: versions generate
      pr-title: "[bot] Synchronize versions of the downstream components"
      pr-body: |
        ## Description
        This pull request updates `jsonnet/versions.yaml` to match with the downstream versions of the monitoring components and regenerates all assets.

        If you wish to perform this manually, execute the following commands from cluster-monitoring-operator repository:
        ```
        make versions
        make generate
        ```
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
